#!/usr/bin/env bash

mkdir -p .git/hooks

ln -sf ../../scripts/pre-commit.hook .git/hooks/pre-commit || exit 1
chmod +x .git/hooks/pre-commit

touch .git/hooks/applied || exit 1

echo
echo "Git hooks are installed successfully."
